# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=200)),
                ('answer', models.BooleanField()),
                ('explanation', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=100)),
            ],
        ),
    ]
