# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='kakaoID',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
