# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180902_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
